version: '3.5'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ng_frontend
    ports:
      - "3000:3000"
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    container_name: ng_backend
    build: 
      context: .app/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    container_name: ng_db
    image: postgres:15.1
    platform: linux/x86_64
    ports:
      - "3002:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
